
services:
  keycloak:
    build: ./keycloak
    image: my_keycloak:latest
    container_name: keycloak
    hostname: keycloak
    command: ['start',"--import-realm","--verbose","--optimized"]
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - shared_network
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    environment:
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_DB=mssql
      - KC_DB_USERNAME=sa
      - KC_DB_PASSWORD=Abcd123!
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_DB_URL=jdbc:sqlserver://mssql:1433;databaseName=keycloak;trustServerCertificate=false;encrypt=false;
      - KC_LOG_LEVEL=INFO,org.infinispan:DEBUG,org.jgroups:DEBUG
    depends_on:
      - mssql

  in-auth:
    build: 
      context: ./in-auth
      dockerfile: InAuthServer/Dockerfile
    container_name: in-auth
    image: in-auth:latest
    ports:
      - 8082:8080
    networks:
      - shared_network
    depends_on:
      - keycloak

  webapi:
    build: ./webapi/dotnetapi
    container_name: webapi
    image: in_webapi:latest
    ports:
      - 5000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - shared_network
    depends_on:
      - keycloak

  krakend:
    build: ./krakend
    container_name: api_gateway
    image: api_gateway:latest
    ports:
      - 8081:8081
    networks:
      - shared_network
    depends_on:
      - keycloak

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - 1433:1433
    volumes:
      - ./mssql:/var/opt/mssql/data
    networks:
      - shared_network
    environment:
      - TZ=Asia/Taipei
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Abcd123!
      - MSSQL_PID=Developer
      - MSSQL_MEMORY_LIMIT=2GB
  #   healthcheck:
  #     test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Abcd123! -Q 'SELECT 1'"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 90s
  init-db:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    entrypoint: /bin/bash -c "sleep 45; /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P Abcd123! -Q 'CREATE DATABASE keycloak;'"
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge