
services:
  keycloak:
    build: ./keycloak
    image: my_keycloak:latest
    container_name: keycloak
    hostname: keycloak
    command: ['start',"--import-realm","--verbose","--optimized",]
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - shared_network
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    environment:
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_DB=mssql
      - KC_DB_USERNAME=sa
      - KC_DB_PASSWORD=Abcd1234
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:sqlserver://mssql:1433;databaseName=keycloak;trustServerCertificate=false;encrypt=false;
      - KC_LOG_LEVEL=INFO,org.infinispan:DEBUG,org.jgroups:DEBUG
    depends_on:
      mssql:
        condition: service_healthy

  webapi:
    build: ./webapi/dotnetapi
    container_name: webapi
    image: in_webapi:latest
    ports:
      - 5000:8080
    networks:
      - shared_network
    depends_on:
      - keycloak

  krakend:
    build: ./krakend
    container_name: api_gateway
    image: api_gateway:latest
    ports:
      - 8081:8081
    networks:
      - shared_network
    depends_on:
      - keycloak

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - 1433:1433
    volumes:
      - ./mssql:/var/opt/mssql/data
    networks:
      - shared_network
    environment:
      - TZ=Asia/Taipei
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Abcd1234
      - MSSQL_PID=Developer
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Abcd1234 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 3

  init-db:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    entrypoint: /bin/bash -c "sleep 30; /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P Abcd1234 -Q 'CREATE DATABASE keycloak;'"
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge